# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.URLField(max_length=100, unique=True, verbose_name='url repositorio del proyecto')),
                ('name_package', models.CharField(max_length=50, unique=True, verbose_name='nombre paquete')),
                ('description_package', models.CharField(max_length=50, verbose_name='descripcion paquete')),
                ('email', models.EmailField(max_length=50, verbose_name='correo del postulador')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_package',),
            },
        ),
        migrations.CreateModel(
            name='Package_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Recibido', max_length=50, verbose_name='estatus del paquete')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulacion.Package')),
            ],
            options={
                'ordering': ('package_id',),
            },
        ),
    ]
