# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='owner',
        ),
    ]
