# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0003_auto_20160902_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 9, 6, 20, 42, 9, 761537, tzinfo=utc), verbose_name='fecha de creacion del paquete'),
            preserve_default=False,
        ),
    ]
