# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0004_package_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description_package',
            field=models.CharField(max_length=200, verbose_name='descripcion paquete'),
        ),
        migrations.AlterField(
            model_name='package',
            name='repository',
            field=models.URLField(max_length=150, unique=True, verbose_name='url repositorio del proyecto'),
        ),
    ]
