# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0005_auto_20161011_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description_package',
            field=models.CharField(max_length=200, unique=True, verbose_name='descripcion paquete'),
        ),
        migrations.AlterField(
            model_name='package',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='correo del postulador'),
        ),
    ]
