# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0008_auto_20161123_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Correo del postulador'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_package',
            field=models.CharField(max_length=50, verbose_name='Nombre del paquete'),
        ),
    ]
