# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0009_auto_20161212_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
    ]
