# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulacion', '0004_package_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion del paquete')),
                ('fecha_actualizada', models.DateTimeField(auto_now=True, verbose_name='fecha para actualizar del paquete')),
                ('name_package', models.CharField(max_length=50, unique=True, verbose_name='nombre paquete')),
                ('status', models.CharField(choices=[('postulado', 'postulado'), ('evaluado', 'evaluado'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado')], default='postulado', max_length=50)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulacion.Package')),
            ],
            options={
                'ordering': ('package_id',),
            },
        ),
    ]
