# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='name_package',
        ),
    ]
