# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0002_auto_20160908_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ('fecha_actualizada',)},
        ),
    ]
