# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0003_auto_20160908_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='package_id',
            new_name='package',
        ),
    ]
