# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import postulacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0004_auto_20160908_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='name_package',
            field=models.CharField(default=datetime.datetime(2016, 9, 9, 14, 23, 41, 610843, tzinfo=utc), max_length=50, unique=True, verbose_name=postulacion.models.Package),
            preserve_default=False,
        ),
    ]
