# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0005_historial_name_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='package',
        ),
        migrations.AlterField(
            model_name='historial',
            name='name_package',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='postulacion.Package'),
        ),
    ]
