# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0006_auto_20160909_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_actualizada',
            field=models.DateField(auto_now=True, verbose_name='fecha para actualizar del paquete'),
        ),
    ]
