# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0007_auto_20160923_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='name_package',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre paquete'),
        ),
    ]
