# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0009_auto_20160923_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='status',
            field=models.CharField(choices=[('1', 'postulado'), ('2', 'evaluado'), ('3', 'aceptado'), ('4', 'rechazado')], default='postulado', max_length=50),
        ),
    ]
