# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0013_auto_20161003_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_actualizada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
