# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0017_auto_20161017_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='status',
            field=models.CharField(choices=[('postulado', 'postulado'), ('evaluado', 'evaluado'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado')], default='postulado', max_length=10),
        ),
    ]
