# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0019_auto_20161026_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador_formulario1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre1', models.BooleanField(default=False, verbose_name='Llave PGP')),
                ('pre2', models.BooleanField(default=False, verbose_name='No excede de los 200 MB')),
                ('pre3', models.BooleanField(default=False, verbose_name='Empaquetado ')),
                ('pre4', models.BooleanField(default=False, verbose_name='Errores de Lintian')),
                ('pre5', models.BooleanField(default=False, verbose_name='No excede el tiempo de contruccion o empaquetado')),
                ('pre6', models.BooleanField(default=False, verbose_name='Documentacion')),
                ('pre7', models.BooleanField(default=False, verbose_name='No ejecuta comandos maliciosos')),
                ('pre8', models.BooleanField(default=False, verbose_name='Terminos de licencia')),
                ('pre9', models.BooleanField(default=False, verbose_name='Empaqueta binarios')),
            ],
        ),
        migrations.AlterField(
            model_name='historial',
            name='name_package',
            field=models.CharField(max_length=50, verbose_name='Nombre del Paquete'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='status',
            field=models.CharField(choices=[('postulado', 'Postulado'), ('evaluado', 'En Evaluacion'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='evaluado', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluador_formulario1',
            name='name_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusSeguimiento.Historial'),
        ),
    ]
