# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0020_auto_20161123_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador_formulario2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusSeguimiento.Evaluador_formulario1')),
            ],
        ),
    ]
