# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0021_evaluador_formulario2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evaluador_formulario1',
            new_name='EvaluadorFormulario1',
        ),
        migrations.RenameModel(
            old_name='Evaluador_formulario2',
            new_name='EvaluadorFormulario2',
        ),
        migrations.RenameField(
            model_name='evaluadorformulario2',
            old_name='observaciones',
            new_name='obs',
        ),
    ]
