# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-25 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0022_auto_20161123_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluadorFormulario1',
            new_name='Evaluador1',
        ),
        migrations.RenameModel(
            old_name='EvaluadorFormulario2',
            new_name='Evaluador2',
        ),
    ]
