# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-29 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0023_auto_20161125_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(choices=[(False, 'main'), (False, 'contrib'), (False, 'non-free')], default=False, max_length=3)),
                ('obs', models.CharField(max_length=200, verbose_name='Observaciones')),
            ],
        ),
        migrations.RenameField(
            model_name='evaluador2',
            old_name='pre',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre1',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre2',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre3',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre4',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre5',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre6',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre7',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre8',
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='pre9',
        ),
        migrations.AddField(
            model_name='evaluador1',
            name='pregunta',
            field=models.CharField(default=datetime.datetime(2016, 11, 29, 16, 50, 2, 661758, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluador2',
            name='respuesta',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3),
        ),
        migrations.AddField(
            model_name='evaluador3',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusSeguimiento.Evaluador1'),
        ),
    ]
