# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0025_auto_20161129_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsEvaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs1', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs2', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs3', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs4', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs5', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs6', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs7', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs8', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('obs9', models.CharField(max_length=200, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='PreEvaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre1', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre3', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre4', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre5', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre6', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre7', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('pre8', models.BooleanField(choices=[(False, 'main'), (False, 'contrib'), (False, 'non-free')], default=False, max_length=3)),
                ('pre9', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('name_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusSeguimiento.Historial')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluador1',
            name='name_package',
        ),
        migrations.RemoveField(
            model_name='evaluador2',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='evaluador3',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Evaluador1',
        ),
        migrations.DeleteModel(
            name='Evaluador2',
        ),
        migrations.DeleteModel(
            name='Evaluador3',
        ),
        migrations.AddField(
            model_name='obsevaluador',
            name='pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusSeguimiento.PreEvaluador'),
        ),
    ]
