# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0026_auto_20161130_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs1',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs2',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs3',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs4',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs5',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs6',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs7',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs8',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs9',
            field=models.CharField(blank=True, default='no hay observaciones', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre1',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre2',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre3',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre4',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre5',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre6',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre7',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre8',
            field=models.BooleanField(choices=[(False, 'main'), (False, 'contrib'), (False, 'non-free')], default=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='preevaluador',
            name='pre9',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5),
        ),
    ]
