# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0027_auto_20161205_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsevaluador',
            name='pre',
        ),
        migrations.RemoveField(
            model_name='preevaluador',
            name='name_package',
        ),
    ]
