# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0028_auto_20161205_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='status',
            field=models.CharField(choices=[('Postulado', 'Postulado'), ('En Evaluacion', 'En Evaluacion'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='En Evaluacion', max_length=10),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs8',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obsevaluador',
            name='obs9',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
    ]
