# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0030_auto_20161213_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preevaluador',
            name='pre8',
        ),
        migrations.AddField(
            model_name='preevaluador',
            name='pre8_0',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='main'),
        ),
        migrations.AddField(
            model_name='preevaluador',
            name='pre8_1',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='contrib'),
        ),
        migrations.AddField(
            model_name='preevaluador',
            name='pre8_2',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='non-free'),
        ),
    ]
